applications:
  - name: microservice-app
    namespace: default
    project: default
    source:
      repoURL: https://github.com/zharuk-alex/my-microservice-project.git
      path: charts/django-app
      targetRevision: main
      # targetRevision: lesson-9
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: microservice-app
    url: https://github.com/zharuk-alex/my-microservice-project.git
    # username: YOUR_USERNAME
    # password: YOUR_PASS

repoConfig:
  insecure: "true"
  enableLfs: "true"
